# Generated by Django 4.2.23 on 2025-08-25 07:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자 목록',
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.UUIDField(blank=True, db_column='chat_id', null=True)),
            ],
            options={
                'verbose_name': '파일 정보',
                'verbose_name_plural': '파일 정보 목록',
                'db_table': 'file_info',
            },
        ),
        migrations.CreateModel(
            name='ReportedConversation',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('report_reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '처리 완료'), ('rejected', '거부됨')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': '신고된 대화',
                'verbose_name_plural': '신고된 대화 목록',
                'db_table': 'reported_conversation',
                'indexes': [models.Index(fields=['chat_id'], name='idx_reported_chat'), models.Index(fields=['user_id'], name='idx_reported_user'), models.Index(fields=['session_id'], name='idx_reported_session')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('store_name', models.CharField(blank=True, max_length=200, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '영수증 정보',
                'verbose_name_plural': '영수증 정보 목록',
                'db_table': 'receipt_info',
                'indexes': [models.Index(fields=['user_id'], name='idx_receipt_user'), models.Index(fields=['status'], name='idx_receipt_status'), models.Index(fields=['created_at'], name='idx_receipt_created')],
            },
        ),
    ]
