# Generated by Django 4.2.23 on 2025-08-20 07:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자 목록',
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='ReportedConversation',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('report_reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '처리 완료'), ('rejected', '거부됨')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': '신고된 대화',
                'verbose_name_plural': '신고된 대화 목록',
                'db_table': 'reported_conversation',
            },
        ),
    ]
