# Generated by Django 4.2.23 on 2025-08-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': '영수증 정보', 'verbose_name_plural': '영수증 정보 목록'},
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='idx_receipt_user',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='idx_receipt_date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
