# Generated by Django 4.2.23 on 2025-08-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileInfo',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.RemoveIndex(
            model_name='reportedconversation',
            name='idx_reported_chat',
        ),
        migrations.RemoveIndex(
            model_name='reportedconversation',
            name='idx_reported_user',
        ),
        migrations.RemoveIndex(
            model_name='reportedconversation',
            name='idx_reported_session',
        ),
    ]
