# Generated by Django 4.2.23 on 2025-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptInfo',
            fields=[
                ('receipt_id', models.UUIDField(primary_key=True, serialize=False)),
                ('file_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('store_name', models.CharField(blank=True, max_length=200, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '영수증 정보',
                'verbose_name_plural': '영수증 정보 목록',
                'db_table': 'receipt_info',
                'managed': False,
            },
        ),
    ]
