# Generated by Django 4.2.23 on 2025-08-25 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('input_s3_key', models.CharField(max_length=500)),
                ('result_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rec_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecResultItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='receipt.recjob')),
            ],
            options={
                'db_table': 'rec_result_item',
                'ordering': ['line_no'],
            },
        ),
        migrations.RemoveField(
            model_name='receiptinfo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='receiptinfo',
            name='user',
        ),
        migrations.CreateModel(
            name='RecResultSummary',
            fields=[
                ('job_id', models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='receipt.recjob')),
                ('store_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('card_company', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number_masked', models.CharField(blank=True, max_length=64, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rec_result_summary',
            },
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
        migrations.DeleteModel(
            name='ReceiptInfo',
        ),
    ]
