# Generated by Django 4.2.23 on 2025-08-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='문서명')),
                ('document_path', models.CharField(max_length=500, verbose_name='문서 경로')),
                ('vector_id', models.CharField(max_length=100, unique=True, verbose_name='벡터 ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='카테고리')),
                ('register_date', models.CharField(blank=True, max_length=20, verbose_name='등록일')),
                ('doc_title', models.CharField(blank=True, max_length=255, verbose_name='문서 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문서 벡터',
                'verbose_name_plural': '문서 벡터들',
                'db_table': 'document_vectors',
                'ordering': ['-created_at'],
            },
        ),
    ]
